config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'issue/delAtt'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :issues do
  resources :comments
  resources :votes
       resources :watches
  end
  resources :users
  root to: "issues#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_attached_file :file, :styles => { :small => "150x150>" }, default_url: "http://clipart-library.com/image_gallery/267356.png"
  validates_attachment_content_type :file, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  belongs_to :issue
  belongs_to :user, optional: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_issue
    before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner, :show]
    before_action :comment_owner, only: [:destroy, :edit, :update]
    skip_before_action :verify_authenticity_token
    
    # GET /issues/:issue_id/comments
    # GET /issues/:issue_id/comments.json
    def index
        @comments = @issue.comments
    end

    # GET /issues/:issue_id/comments/:id
    # GET /issues/:issue_id/comments/:id.json
    def show
    end

    def create
        @user_aux = authenticate
        if @user_aux != nil
            if !params[:comment][:content].blank?
                @comment = @issue.comments.create(params[:comment].permit(:content))
                @comment.user_id = @user_aux.id
                if @comment.save
                    redirect_to issue_path(@issue)
                else
                    render 'new'
                end
            else
                redirect_to issue_path(@issue)
            end
        else
            redirect_to @issue, notice: 'You must be logged in' 
        end
    end

    def destroy
        @comment.destroy
        redirect_to @issue, status: :see_other
    end

    def edit
    end

    def update
        if @comment.update(params[:comment].permit(:content))
            redirect_to @issue, status: :see_other
        else 
            render 'edit'
        end
    end

    private
    def find_issue
        @issue = Issue.find(params[:issue_id])
    end

    private 
    def find_comment
        @comment = @issue.comments.find(params[:id])
    end

    def comment_owner
        @user_aux = authenticate
        unless @user_aux.id == @comment.user_id
            flash[:notice] = "You shall not pass!"
            redirect_to @issue
        end
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= "Comment".pluralize(@comments.count) %> (<%= @comments.count %>)
<br>
<% @comments.each do |comment|%>
<div class="container">
<div class="row">
<div class="col-1">
<% if comment.has_attribute?(:user_id) and comment.user != nil %>
    <img class="perfil_image" src ="<%=comment.user.imageurl%>">
<% end %>
</div>

<div class="col-11">
<% if comment.has_attribute?(:user_id) and comment.user != nil %>
  <span class="user-name"><%= comment.user.name %> </span>
<% else %>
    <b> !!!! ERROR ACTUALIZA EL PROYECTO O COMUNICATE CONMIGO !!!!: </b> 
<% end %>

 <span class="time-ago"><%= time_ago_in_words(comment.created_at)%></span>
 <p> <%= comment.content %></p>
 <p> <% if comment.file.present? %>

    <%= link_to "Download attachment", comment.file.url(:original, false) %>
 
  <%end%></p>
<% if current_user == comment.user %>
    <%= link_to "Edit", edit_issue_comment_path(comment.issue, comment)%>
    <%= link_to "Delete", [comment.issue, comment], method: :delete%>
    <br>
<% end%>
</div>
</div>
</div>
<% end %>

app/views/comments/_form.html.erb
<div class="container">
    <div class="row">
        <% if current_user %>
            <div class="col-1">
                <img class="user-image" src ="<%=current_user.imageurl%>">
            </div>

            <div class="col-11">
                <%= form_for([@issue, @issue.comments.build], html: { multipart: true}) do |f| %>
                <%= f.text_area :content , class: 'form-control'%>
                <%= f.label :file, "File" %>
                <%= f.file_field :file %>
                <br>
                <%= f.submit "Comment", :class => 'button-primary'%>
                <% end %>
            </div>
        <% end %>
    
    </div>
</div>

app/views/comments/edit.html.erb
<%= form_for([@issue, @comment]) do |f| %>

<div class="container pt-5">
    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
            Comentario
        </div>
      </div>

      <div class="col-5">
        <%= f.text_area :content, :class => "form-control"%>
      </div>
    </div>

     <div class="row justify-content-end">
        <div class="actions">
          <span class="mx-3"><%= f.submit :class =>'button-primary' %></span>
        </div>
        <span class="mx-3 no-bold">
<%= link_to 'Cancel', @issue, class: 'link-secondary not-bold align-middle' %></span>
    </div>
</div>
<% end %>