config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  post 'issue/delAtt'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :issues do
  resources :comments
  resources :votes
       resources :watches
  end
  resources :users
  root to: "issues#index"
end

app/models/issue.rb
class Issue < ApplicationRecord
    
    has_attached_file :file, :styles => { :small => "150x150>" }, default_url: "http://clipart-library.com/image_gallery/267356.png"
    validates_attachment_content_type :file, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    
    ALL_PRIORITIES = ["trivial", "minor", "major", "critical", "blocker"]
    
    validates_inclusion_of :priority, :in => ALL_PRIORITIES
    
    
    ALL_TYPES = ["bug", "enhancement", "proposal", "task"]
    
    validates_inclusion_of :kind, :in => ALL_TYPES  
    
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    belongs_to :assignee, optional: true, :class_name => 'User', foreign_key: 'assignee_id'
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :watches, dependent: :destroy
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /issues
  # GET /issues.json
  def index
     
    #status filters
    if params[:status] == "new"
      @issues = Issue.where(status: ["new"])
    elsif params[:status] == "open" or params[:status] == "new"
      @issues = Issue.where(status: ["open", "new"])
    elsif params[:status].present?
      @issues = Issue.where(status: [params[:status]])
    #kind filters
    elsif params[:kind].present?
      @issues = Issue.where(kind: [params[:kind]])
    #priority filters
    elsif params[:priority].present?
      @issues = Issue.where(priority: [params[:priority]])
    #user filters
    elsif params[:assignee_id].present?
      @issues = Issue.where(assignee_id: [params[:assignee_id]])
    #myissues
    elsif current_user.present? and params[:user_id] == "m"
      @issues = Issue.where(user_id: current_user.id)
    elsif current_user.present? and params[:user_id] == "w"
      
      @issues = Issue.joins(:watches).where(['watches.issue_id = issues.id AND watches.user_id = ?', current_user.id])
      
    else
      @issues = Issue.all
    end
    
    if params[:sort].present?
      if params[:dir] == "down"
        @issues = @issues.order(params[:sort]).reverse_order
      else
        @issues = @issues.order(params[:sort])
      end
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @comments = Comment.where(issue_id: @issue).order("created_at ASC")
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.status = "new";
    
     if @issue.file.present?
        @comment = @issue.comments.new(content: "-- File attached", user_id: @issue.user.id)
        @comment.save!
     end
     
    respond_to do |format|
      @user_aux = authenticate
      if (@user_aux.nil?)
        format.json { render json: @issue.errors, status: 403}
      else
        @issue.user_id = @user_aux.id;
        if @issue.save
          format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
          format.json { render :show, status: :created, location: @issue }
        else
          format.html { render :new }
          format.json { render json: @issue.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      @user_aux = authenticate
      if (!@user_aux.nil? and @user_aux.id == @issue.user_id)
        if @issue.update(issue_params)
          if @issue.saved_changes.include?(:status)
            @comment = @issue.comments.new(content: "•   changed status to " + @issue.status, user_id: @issue.user.id)
            @comment.save!
          end
          format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
          format.json { render :show, status: :ok, location: @issue }
        else
          format.html { render :edit }
          format.json { render json: @issue.errors, status: :unprocessable_entity }
        end
      else 
        format.json { render json: @issue.errors, status: 403}
      end
    end
  end
  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def delAtt
    @issue.file.destroy
    @issue.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
       params.require(:issue).permit(:title, :description, :kind, :priority, :status, :assignee_id, :file)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for @issue, html: { multipart: true } do |form| %>

  
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
          <%= form.label :title %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
          <%= form.text_field :title, id: :issue_title, class: 'form-control' %>
        </div>
      </div>
    </div>



    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
          <%= form.label :description %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
          <%= form.text_area :description, id: :issue_description , class: 'form-control'%>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
          <%= form.label :kind %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
          <%= form.select :kind, [['bug'],['enhancement'],['proposal'],['task']], class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
          <%= form.label :priority %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
          <%= form.select :priority, [['trivial'],['minor'],['major'],['critical'],['blocker']] , class: 'form-control'%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
          <%= form.label :assignee %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
          <%= form.collection_select :assignee_id, User.order(:name),:id,:name, include_blank: true , class: 'form-control'%>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
        <%= form.label :file, "File" %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
        <%= form.file_field :file, class: 'form-control-file' %>
        </div>
      </div>
    </div>

    <div class="row justify-content-end">
        <div class="actions">
          <span class="mx-3"><%= form.submit :class =>'button-primary' %></span>
        </div>
        <span class="mx-3 no-bold"><%= link_to 'Cancel', issues_path, class: 'link-secondary not-bold align-middle' %></span>
    </div>

  </div>
<% end %>

app/views/issues/_formEdit.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
    <%= form.label :title %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
    <%= form.text_field :title, id: :issue_title, class: 'form-control'  %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
    <%= form.label :description %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
    <%= form.text_area :description, id: :issue_description, class: 'form-control'  %>
        </div>
      </div>
    </div>
  
    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
    <%= form.label :status %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
    <%= form.select :status, [['open'],['on hold'],['resolved'],['duplicate'],['invalid'],['wontfix'],['closed']], default: @issue.status, class: 'form-control'  %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
    <%= form.label :kind %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
    <%= form.select :kind, [['bug'],['enhancement'],['proposal'],['task']], class: 'form-control'  %>
        </div>
      </div>
    </div>



    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
    <%= form.label :priority %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
    <%= form.select :priority, [['trivial'],['minor'],['major'],['critical'],['blocker']], class: 'form-control'  %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
    <%= form.label :assignee %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
    <%= form.collection_select :assignee_id, User.order(:name),:id,:name, include_blank: true , class: 'form-control' %>
        </div>
      </div>
    </div>
      
    <div>
      <% if @issue.file.present? %>
        <!-- %= button_to 'Delete attachment', issue_delAtt_path, method: :post %-->
      <%else%>
        <!-- Other fields go here... -->

    <div class="row">
      <div class="col-2">
        <div class="field not-bold text-right">
        <%= form.label :file, "File" %>
        </div>
      </div>

      <div class="col-5">
        <div class="field">
        <%= form.file_field :file, class: 'form-control-file' %>
        </div>
      </div>
    </div>
      <%end%>
     </div>

     <div class="row justify-content-end">
        <div class="actions">
          <span class="mx-3"><%= form.submit :class =>'button-primary' %></span>
        </div>
        <span class="mx-3 no-bold">
<%= link_to 'Cancel', @issue, class: 'link-secondary not-bold align-middle' %></span>
    </div>


  </div>
<% end %>

app/views/issues/edit.html.erb
<p class="pt-5 pb-3">Edit issue</p>
<%= render 'formEdit', issue: @issue %>

app/views/issues/index.html.erb
<header>        
    <div class="filter-container">
        <p class="filter-label">Filter by:</p>
        <ul class="filter-status">
        <li class="filter" <% if request.env['ORIGINAL_FULLPATH'] == "/issues"%> aria_pressed="true"  <%end%>>
            <a <% if request.env['ORIGINAL_FULLPATH'] == "/issues"%> id="pruebaF"<%end%> href="/issues">All</a>
        </li>
        <li class="filter" <% if request.env['ORIGINAL_FULLPATH'] == "/issues?status=new&status=open"%> aria_pressed="true"  <%end%>>
            <a <% if request.env['ORIGINAL_FULLPATH'] == "/issues?status=new&status=open"%> id="pruebaF"<%end%> href="/issues?status=new&amp;status=open">Open</a>
        </li>
        <% if current_user %>
        <li class="filter" <% if request.env['ORIGINAL_FULLPATH'] == "/issues?user_id=m"%> aria_pressed="true"  <%end%>>
            <a <% if request.env['ORIGINAL_FULLPATH'] == "/issues?user_id=m"%> id="pruebaF"<%end%> href="/issues?user_id=m">My issues</a>
        </li>
        <li class="filter" <% if request.env['ORIGINAL_FULLPATH'] == "/issues?user_id=w"%> aria_pressed="true"  <%end%>>
            <a <% if request.env['ORIGINAL_FULLPATH'] == "/issues?user_id=w"%> id="pruebaF"<%end%> href="/issues?user_id=w">Watching</a>
        </li>
        <% end %>
        </ul>
    </div>
    <div>
    <% if current_user %>
    <span id = "newIssue" style="float:right;"> <%= link_to 'Create Issue', new_issue_path %> </span>
    <% end %>   
    </div>
        <h1>Issues<span class="secondary">(<%= (@issues.count{ |u| [u.title] })%>)</span></h1>
</header>
<p id="notice"><%= notice %></p>
<table class = "table">
  <thead class = "table_header">
    <tr id="leyendaTR">
      <th class="leyenda">Title <%= link_to "↑", "/issues?sort=id" %> <%= link_to "↓", "/issues?sort=id&dir=down" %></th>
      <th class="leyenda">Kind <%= link_to "↑", "/issues?sort=kind" %> <%= link_to "↓", "/issues?sort=kind&dir=down" %></th>
      <th class="leyenda">Priority <%= link_to "↑", "/issues?sort=priority" %> <%= link_to "↓", "/issues?sort=priority&dir=down" %></th>
      <th class="leyenda">Status <%= link_to "↑", "/issues?sort=status" %> <%= link_to "↓", "/issues?sort=status&dir=down" %></th>
      <th class="leyenda">Votes </th>
      <th class="leyenda">Assignee <%= link_to "↑", "/issues?sort=assignee_id" %> <%= link_to "↓", "/issues?sort=assignee_id&dir=down" %></th>
      <th class="leyenda">Created <%= link_to "↑", "/issues?sort=created_at" %> <%= link_to "↓", "/issues?sort=created_at&dir=down" %></th>
      <th class="leyenda">Updated <%= link_to "↑", "/issues?sort=updated_at" %> <%= link_to "↓", "/issues?sort=updated_at&dir=down" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class = "table_body">
    <% @issues.each do |issue| %>
      <tr>
        <td><%= link_to '#' + issue.id.to_s + ': ' + issue.title, issue %></td>
        <% if issue.kind == "bug" %>
	<td><%= link_to image_tag("bug.svg"), "/issues?kind=bug" %></td>
        <% end %>
	<% if issue.kind == "enhancement"%>
	<td><%= link_to image_tag("enhancement.svg"), "/issues?kind=enhancement" %></td>
        <% end %>
 	<% if issue.kind == "proposal"%>
	<td><%= link_to image_tag("proposal.svg"), "/issues?kind=proposal" %></td>
        <% end %>
	<% if issue.kind == "task"%>
	<td><%= link_to image_tag("task.svg"), "/issues?kind=task" %></td>
        <% end %>
	<% if issue.priority == "trivial"%>
	<td><%= link_to image_tag("trivial.svg"), "/issues?priority=trivial" %> </td>
	<% end %>
	<% if issue.priority == "minor"%>
	<td><%= link_to image_tag("minor.svg"), "/issues?priority=minor" %> </td>
	<% end %>
	<% if issue.priority == "major"%>
	<td><%= link_to image_tag("major.svg"), "/issues?priority=major" %></td>
	<% end %>
	<% if issue.priority == "critical"%>
	<td><%= link_to image_tag("critical.svg"), "/issues?priority=critical" %></td>
	<% end %>
	<% if issue.priority == "blocker"%>
	<td><%= link_to image_tag("blocker.svg"), "/issues?priority=blocker" %></td>
	<% end %>
	<% if issue.status == "new" %>
    <td class = "status" ><%= link_to issue.status, "/issues?status=new", :id => "status-new" %></td>
    <%end%>
    <% if issue.status == "open" %>
    <td class = "status"><%= link_to issue.status, "/issues?status=open", :id => "status-open" %></td>
    <%end%>
    <% if issue.status == "on hold" %>
    <td class = "status" ><%= link_to issue.status, "/issues?status=on_hold", :id => "status-on_hold" %></td>
    <%end%>
    <% if issue.status == "duplicate" %>
    <td class = "status"><%= link_to issue.status, "/issues?status=duplicate", :id => "status-duplicate" %></td>
    <%end%>
    <% if issue.status == "invalid" %>
    <td class = "status"><%= link_to issue.status, "/issues?status=invalid", :id => "status-invalid" %></td>
    <%end%>
    <% if issue.status == "wontfix" %>
    <td class = "status"><%= link_to issue.status, "/issues?status=wontfix", :id => "status-wontfix" %></td>
    <%end%>
    <% if issue.status == "closed" %>
    <td class = "status"><%= link_to issue.status, "/issues?status=closed", :id => "status-closed" %></td>
    <%end%>
    <% if issue.status == "resolved" %>
    <td class = "status" ><%= link_to issue.status, "/issues?status=resolved", :id => "status-resolved" %></td>
    <%end%>
    <% if issue.status != "new" and issue.status != "open" and issue.status != "on hold" and issue.status != "duplicate" and issue.status != "invalid" and issue.status != "wontfix" and issue.status != "closed" and issue.status != "resolved" %>
    <td></td>
    <% end %>
    <% if issue.votes.count > 0 %>
        <td id = "vote">
        <%= issue.votes.count %>
        </td>
    <% else %>
        <td></td>
        <% end %>
    <td style="vertical-align:middle;"><% if issue.assignee.present? %>
        <img class="perfil_image_table" src ="<%=issue.assignee.imageurl%>">
        <%= link_to issue.assignee.name, "/issues?assignee_id=" + issue.assignee_id.to_s, :style=>"vertical-align: middle;" %>
        <% end %>
    </td>        
    
        <td><%= time_ago_in_words(issue.created_at) + " ago" %></td>
        <td><%= time_ago_in_words(issue.updated_at) + " ago" %></td>
        <!--<td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        
        <% if current_user != nil %>
        <td>
        <% pre_watch = issue.watches.find { |watch| watch.user_id == current_user.id} %>
          <% if pre_watch %>
            <%= link_to image_tag("unwatch.svg", :id=>"watch"), issue_watch_path(issue, pre_watch), method: :delete  %>
          <% else %>
            <%= link_to image_tag("watch.svg", :id=>"watch"), issue_watches_path(issue), method: :post%>
          <% end %>
        </td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/issues/new.html.erb
<p class="pt-5 pb-3">Create issue</p>

<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<div class="container mx-auto">
  <p id="notice"><%= notice %></p>



  <div class="row">
    <div class="col-8">
      <span class="issue-title"><%= @issue.title %></span>
      <br>
      <span>Issue #<%= @issue.id %></span>
      <span class="title-status"><%= @issue.status %></span>
      <br>
      <div class="container my-4">
        <div class="row">
          <div class="col-1">
            <img class="user-image" src ="<%=@issue.user.imageurl%>">
          </div>


          <div class="col-11">
            <span class="user-name"><%= @issue.user.name %> </span>
            <span class="not-bold">created an issue </span>
            <span class="time-ago not-bold"><%= time_ago_in_words(@issue.created_at)%></span>
            <% if @issue.description.blank? %>
              <p class="not-bold my-2">No description provided.</p>
            <% else %>
              <p class="not-bold my-2"><%= @issue.description %></p>
            <% end %>
            <div>
              <% if @issue.file.present? %>
                <%= link_to "Download attachment", @issue.file.url(:original, false) %>
              <%end%>
            </div>
          </div>
        </div>
      </div>

      <hr>
      <%= render 'comments/comment'%>
      <br>
      <%= render 'comments/form'%>
    </div>

    <div class="col-4 my-5">
      <% if @issue.user == current_user %>
        <%= link_to 'Edit', edit_issue_path(@issue), :class => "button-primary2 "%>

      <% end %>
      <div class="issue-attrs">
      <table class="table table-sm">
        <tbody>
          <tr class="noHover">
            <th scope="row">Asignee</th>
            <td>
            <% if @issue.assignee.present? %>
              <%= @issue.assignee.name %>
            <% else %>
              &ndash; 
            <% end %>
            </td>
          </tr>
          <tr class="noHover">
            <th scope="row">Type</th>
            <td>
            <%= @issue.kind %>
            </td>
          </tr>
          <tr class="noHover">
            <th scope="row">Priority</th>
            <td>
            <%= @issue.priority %>
            </td>
          </tr>
          <tr class="noHover">
            <th scope="row">Status</th>
            <td>
            <%= @issue.status %>
            </td>
          </tr>
          <tr class="noHover">
            <th scope="row">Votes</th>
            <td>
            <% if current_user %>
              <% pre_vote = @issue.votes.find { |vote| vote.user_id == current_user.id} %>  
              <% if pre_vote %>
                <span class="counter-active"><%= @issue.votes.count %></span>
                <%= link_to 'Remove vote', issue_vote_path(@issue, pre_vote), method: :delete , :class => "link-secondary"%>
              <% else %>
                <span class="counter-inactive"><%= @issue.votes.count %></span>
                <%= link_to 'Vote for this issue', issue_votes_path(@issue), method: :post , :class => "link-secondary"%>
              <% end %>
            <% else %>
              <span class="counter-inactive"><%= @issue.votes.count %></span>
            <% end %>
            </td>
          </tr>
          <tr class="noHover">
            <th scope="row">Watchers</th>
            <td>
              <% if current_user %>
                <% pre_watch = @issue.watches.find { |watch| watch.user_id == current_user.id} %>
                <% if pre_watch %>
                  <span class="counter-active"><%= @issue.watches.count %></span>
                  <%= link_to 'Stop watching', issue_watch_path(@issue, pre_watch), method: :delete, :class => "link-secondary" %>
                <% else %>
                  <span class="counter-inactive"><%= @issue.watches.count %></span>
                  <%= link_to 'Watch this issue', issue_watches_path(@issue), method: :post, :class => "link-secondary" %>
                <% end %>
              <% else %>
                <span class="counter-inactive"><%= @issue.watches.count %></span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>